version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout

      - run: npm install
      - run: npm run lint:all
      - run: npm run build:min

      - run: mkdir -p reports/junit
      - run:
          command: npm run test:junit
          environment:
            JEST_JUNIT_OUTPUT: "./reports/junit/js-common-test-results.xml"

      - run: npm run check-typescript

      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh

      - store_test_results:
          path: reports/junit/
      - store_artifacts:
          path: reports/junit/
