repo:
  public: js-client-sdk
  private: js-client-sdk-private

publications:
  - url: https://www.npmjs.com/package/launchdarkly-js-client-sdk
    description: npm

template:
  name: npm

documentation:
  githubPages: true
  title: LaunchDarkly JavaScript SDK
